In [ ]:
import numpy as np

In [ ]:
a = np.array([1,2,3,4])
b = np.array([5.2,6,7,8],dtype = "float")
c = a+b
c

In [ ]:
np.zeros(9,dtype = "int").reshape(3,3)

In [ ]:
np.ones((3,5),dtype = "int")

In [ ]:
np.full((3,5),6)

In [ ]:
np.full(3,10)

In [ ]:
np.arange(1,10).reshape(3,3)

In [ ]:
np.linspace(0,1,7)

In [ ]:
np.random.normal(1,10,(3,3))

In [ ]:
np.random.randint(1,10,(2,2))

In [ ]:
a = np.random.randint(1,10,size = (3,3))
a

In [ ]:
a.ndim

In [ ]:
a.size

In [ ]:
a.shape

In [ ]:
a = np.arange(1,10).reshape(3,3)
a

In [ ]:
a = np.arange(1,5)
b = np.arange(5,9)
c = np.concatenate([a,b])
c

In [ ]:
a = np.arange(1,5).reshape(2,2)
np.concatenate([a,a],axis=1)


In [ ]:
a,b,c = np.split(c,[2,4])

In [ ]:
a

In [ ]:
b

In [ ]:
c.reshape(2,2)

In [ ]:
a = np.arange(1,10).reshape(3,3)
a

In [ ]:
np.vsplit(a,[2])

In [ ]:
np.hsplit(a,[2])

In [ ]:
a = np.random.randint(1,10,5)
a

In [ ]:
a[-2]

In [ ]:
a = np.random.randint(1,10,size=(4,4))
a

In [ ]:
a

In [ ]:
b = a[1:3,:].copy()
b[0,2] = 25
b
a

array([[8, 8, 6, 6],
       [1, 3, 8, 8],
       [1, 1, 8, 6],
       [5, 7, 4, 2]])

In [ ]:
b = a[:,0]
c = a[:,1]
z = np.concatenate([b,c]).reshape(len(z),1)
z

array([[8],
       [1],
       [1],
       [5],
       [8],
       [3],
       [1],
       [7]])

In [ ]:
al = [np.arange(2,7,2)]
a = np.arange(1,10)
a[al]

array([[3, 5, 7]])

In [ ]:
a = np.arange(1,10).reshape(3,3)
a


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
a = np.arange(10)
a[a<2]

array([0, 1])

In [ ]:
a<3

array([ True,  True,  True, False, False, False, False, False, False,
       False])

In [ ]:
np.zeros((2,2,2,2))

array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]])

In [ ]:
a = np.arange(3)
np.concatenate([a,a,a]).reshape(3,3)

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [ ]:
a = np.ones((5,5),dtype=int)
a[1:4,1:4] = 0
a[2,2] = 9
a

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
a = np.array([[1,0,3],
              [4,5,2]])

In [ ]:
np.min(a,axis=0 )

array([1, 0, 2])

In [ ]:
a = np.arange(1,31).reshape(6,5)
a


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [ ]:
a[[0,1,2,3],[1,2,3,4]]

array([ 2,  8, 14, 20])

In [ ]:
a[[0,4,5],3:]

array([[ 4,  5],
       [24, 25],
       [29, 30]])

In [ ]:
a = np.random.randint(10,size=(10,10))
a[:,2:6]


array([[4, 5, 3, 1],
       [9, 9, 7, 0],
       [3, 2, 8, 7],
       [6, 6, 0, 3],
       [6, 1, 7, 5],
       [3, 0, 9, 9],
       [5, 4, 8, 5],
       [2, 7, 7, 5],
       [8, 9, 3, 2],
       [8, 9, 8, 8]])

In [ ]:
a

array([[4, 6, 4, 5, 3, 1, 6, 2, 3, 0],
       [4, 1, 9, 9, 7, 0, 0, 9, 7, 7],
       [4, 7, 3, 2, 8, 7, 8, 1, 7, 5],
       [7, 8, 6, 6, 0, 3, 1, 4, 6, 5],
       [3, 8, 6, 1, 7, 5, 6, 2, 1, 8],
       [2, 5, 3, 0, 9, 9, 5, 6, 0, 4],
       [2, 8, 5, 4, 8, 5, 7, 0, 3, 7],
       [6, 0, 2, 7, 7, 5, 0, 2, 6, 2],
       [4, 5, 8, 9, 3, 2, 0, 0, 7, 0],
       [7, 7, 8, 9, 8, 8, 7, 7, 5, 0]])